# Generated by Django 3.2.9 on 2022-03-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0002_auto_20220326_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='Salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sams.salesperson'),
        ),
    ]
