# Generated by Django 4.0.3 on 2022-03-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0004_rename_salesperson_show_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
