# Generated by Django 3.2.9 on 2022-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0005_remove_ticket_price_alter_ticket_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='abal',
            new_name='available_bal',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='aord',
            new_name='available_ord',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='pbal',
            new_name='price_bal',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='pord',
            new_name='price_ord',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='nbal',
            new_name='total_bal',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='nord',
            new_name='total_ord',
        ),
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
