# Generated by Django 3.2.9 on 2022-03-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0006_auto_20220328_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerk',
            name='balance_sheet',
        ),
        migrations.RemoveField(
            model_name='clerk',
            name='user',
        ),
        migrations.AddField(
            model_name='showmanager',
            name='is_clerk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showmanager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
