# Generated by Django 3.2.9 on 2022-03-28 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sams', '0007_auto_20220328_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showmanager',
            name='is_clerk',
        ),
        migrations.RemoveField(
            model_name='showmanager',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='clerk',
            name='balance_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sams.transaction'),
        ),
        migrations.AddField(
            model_name='clerk',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
