# Generated by Django 3.2.9 on 2022-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0008_auto_20220328_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='is_clerk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_salesperson',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='showmanager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
