# Generated by Django 3.2.9 on 2022-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0010_auto_20220328_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='salescommission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='percent_commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='total_commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
