# Generated by Django 3.2.9 on 2022-03-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0013_expenditure_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='amount_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
